### ISSUE TITLE
Format Selection ?

### ISSUE THREAD

**Issue by pcarbonn** [gbuktenica/Unicode-Substitutions#2]
I'm using the extension to easily enter unicode.  For example I type ~, then replace ~ by ¬
```
    {
      "invalid": "~",
      "valid": "\\u00AC",
      "message": "Not."
    }
```
However, I would like to be able to apply the changes to selected text, not the full document.

**Comment by gbuktenica** [comment]
That is a use case I had not thought of. 
This functionality can be added as it is a minor change to how VS Code passes the text to the plugin.

**Comment by gbuktenica** [comment]
Resolved with:
https://github.com/gbuktenica/Unicode-Substitutions/releases/tag/v2.2.0
