### ISSUE TITLE
Does not work with PowerShell extension

### ISSUE THREAD

**Issue by MSIH** [gbuktenica/Unicode-Substitutions#5]
I use VS code mostly for PowerShell. I have the VS Code extension for Powershell installed. The first time trying to format Powershell after installing Unicode-Substitutions, I get prompted to select formatter. The choice is PowerShell or Unicode-Substitution,

**Comment by gbuktenica** [comment]
This is a limitation in VS code. 
This thread talks about ways to overcome this:
https://stackoverflow.com/questions/49428648/multiple-formatters-in-visual-studio-code

**Comment by gbuktenica** [comment]
Note that since March 2019 "Format Document With" will allow a user to format a file with either extension on the fly
https://code.visualstudio.com/updates/v1_33#_default-formatter-selection
